name: smart_insti_app
version: 1.0.0+1
description: "This app aims to solve the day-to-day problems that students and faculty face in IIT Bhilai and aims to consolidate a lot of useful applications into a single app."
publish_to: 'none'

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^14.7.2
  responsive_framework: ^1.5.1
  awesome_notifications: ^0.10.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  search_choices: ^2.2.7
  calendar_date_picker2: ^1.1.8
  logger: ^2.0.2+1
  flutter_typeahead: ^5.0.2
  file_picker: ^8.3.1
  grouped_list: ^6.0.0
  slide_switcher: ^1.1.2
  awesome_snackbar_content: ^0.1.1
  animated_toggle_switch: ^0.8.0
  syncfusion_flutter_sliders: ^28.2.3
  fl_chart: ^0.70.2
  dio: ^5.4.0
  animated_text_kit: ^4.2.2
  image_picker: ^1.0.7
  image_cropper: ^9.0.0
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.2.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1

dependency_overrides:
  vm_service: 14.3.0  # Pinned to avoid conflicts with flutter_test

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
  fonts:
    - family: GoogleSansFlex
      fonts:
        - asset: lib/assets/fonts/google_sans_flex.ttf
    - family: RobotoFlex
      fonts:
        - asset: lib/assets/fonts/roboto_flex.ttf
    - family: Jost
      fonts:
        - asset: lib/assets/fonts/Jost-Regular.ttf
        - asset: lib/assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Jost-Light.ttf
          weight: 300
    - family: Lexend
      fonts:
        - asset: lib/assets/fonts/Lexend-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Lexend-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Lexend-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins-Regular.ttf
          weight: 400
