class RouteConstants {
  static const Map<String, String> routeTitles = {
    '/user_home/news': "Campus Feed",
    '/user_home/events': "Explore Events",
    '/user_home/links': "Useful Links",
    '/user_home/faculty_profile': "Faculty Profile",
    '/user_home/student_profile': "My Profile",
    '/user_home/room_vacancy': "Room Vacancy",
    '/user_home/lost_and_found': "Lost & Found",
    '/user_home/timetables': "My Schedules",
    '/user_home/timetables/editor': "Timetable Editor",
    '/user_home/clubs': "Student Bodies",
    '/user_home/favorites': "My Wishlist",
    '/user_home/campus-posts': "Campus Posts",
    '/user_home/polls': "Campus Polls",
    '/user_home/broadcast': "Broadcast",
    '/user_home/chat_room': "Community Chat",
    '/user_home/mess_menu': "Mess Menu",
    '/user_home/complaints': "Feedback & Support",
    '/user_home/chat_list': "Messages",
    '/user_home/chat_list/chat': "Private Chat",
    '/user_home/marketplace': "Marketplace",
    '/user_home/marketplace/add': "List Item",
    '/user_home/alumni': "Alumni Network",
    '/user_home/leaderboard': "Leaderboard",
    '/user_home/settings': "Settings",
    '/user_home/analytics': "Analytics",
    '/user_home/resources': "Library Resources",
    '/user_home/resources/add': "Add Resource",
    '/user_home/academics': "Academics",
    '/user_home/academics/courses': "My Courses",
    '/user_home/academics/timetable': "Class Timetable",
    '/user_home/academics/curriculum': "Curriculum",
    '/user_home/academics/departments': "Departments",
  };
}
